### ISSUE TITLE
My Leaves - Suggestion

### ISSUE THREAD

**Issue by georgisoft2020** [scavasoft/attendor-issues#10]
![image](https://user-images.githubusercontent.com/74551563/137088614-208b0d43-7bab-4d9e-93a4-4d278643277b.png)

**Comment by plamendp** [comment]
- Dates must become clickable as a mean to start the "booking" process (the same dialog as "Book a leave" with starting date filled). 
- Further enhancement is to click-and-drag to mark the range. Not important.
