### ISSUE TITLE
Set of "Date of birth" is not allowing the save button to be pressed

### ISSUE THREAD

**Issue by dilyanatanasov177** [scavasoft/attendor-issues#12]
When I set my birth date I am not able to save the change because the button doesn't get enabled

![image](https://user-images.githubusercontent.com/74898271/137319187-4be184d3-3edb-4f20-a63d-81c53c882a9e.png)

**Comment by plamendp** [comment]
Cannot confirm. Check other fields (required, matching password, etc.).
