### ISSUE TITLE
[Suggestion] UX Flow -> Projects page

### ISSUE THREAD

**Issue by nuyomi** [scavasoft/attendor-issues#2]
Given I am a user with access to the projects page
And I am browsing the listing of the said page
When I open the ellipsis menu on X project
And I click "Edit Project"
Then I expect to see a full page where I can edit all data concerning the said project

Suggestions:
- Rename "Edit Project" to "Quick Edit" or "Edit Details"
- Rename "Project Details" to "Edit Project"

Reasoning:
- The "Project Details" page is not simply a read-only page, and provides a lot more editing options, as assigning units, deleting projects, on top of editing the base information
- The "Edit Project" provides only options to edit all the fields, already available for edit in the Project Detail's page -> Details tab

**Comment by plamendp** [comment]
Good point. Actually, many other action-drop-down menus have similar names and must be renamed accordingly. 

"**Quick Edit**":  Dialog to edit basic properties
"**Edit Something**" (or just "**Edit**" ?): Separate page for editing all item properties
