### ISSUE TITLE
[Clarification] Projects page -> "User" filter

### ISSUE THREAD

**Issue by nuyomi** [scavasoft/attendor-issues#3]
What's the purpose of the "User filter"?
The usage of it makes no changes to the table, and there is no visual field with "User" to see what's to be filtered by it.

**Comment by plamendp** [comment]
Unit filter: list only projects where selected unit is involved (contract)
User filter: list only projects where selected User is involved (through unit membership and unit contracts).

Both not implemented yet. 
Must be implemented.
