### ISSUE TITLE
[Suggestion] UX Flow -> Profile Page

### ISSUE THREAD

**Issue by nuyomi** [scavasoft/attendor-issues#4]
Given I am a user
And I want to change my password
And I am already at "Profile" page
When I look over the page
Then I expect to quickly spot the change password functionality

Reasoning:
- The top bar has a lot of options, and the attention first falls to the tabs on the main container
- The password change can be a separate tab, with two fields - one for writing, other for confirming the written password

Additional:
- Also, the profile tab usually, as in github, provides the public information that can be accessible by other users, so there could also be an Account tab, where the e-mail and other account-related options can be accessible (along with the password)

**Comment by plamendp** [comment]
Agree on "Change password" action location - perhaps will go as a button in "Profile" tab content, quickly visible.
As for the "Profile" - "Account" separation of data - yes, but not for now. It will be done when we have more user-related data at hand.
